### PR TITLE
New Level: Hijack

### PR DESCRIPTION
**Pull request by AgeManning**
I've added a new level, which I think may be instructive for solidity devs. 

It's not bug or hack, but simply uses the fact that contract addresses are deterministic. This level uses the fact that contracts can be deployed to addresses which already hold eth and thus can withdraw the eth from seemingly locked addresses.

### CODE REVIEW

**Comment by ajsantander** [comment]
Hi @AgeManning, thx for this amazing level/idea.
(And yes, sorry for the extreme delay in checking this PR out, it has been too busy at Zeppelin).

I really like the level, and it got me thinking about possible twists that could make it even more interesting. More interesting as in with a more dramatic outcome and a simpler implementation at the same time.

Options:

a) Imagine a VaultFactory that spawns Vaults with funds that can only be extracted by vault owners. An attacker may know the destination address of an upcoming vault and try to hijack it by using assembly's create2 opcode. This opcode allows you to deploy a contract at an address of your choosing. I'm not even sure if this could work on EVEN regular addresses with funds in them already. Anyways, create2 is a "C" type opcode, that is, it will only be usable in Constantinople, so this is option is a no go for now. I wonder if it will ever make sense for create2 to exists.... it would make too many attacks possible As far as I know, there is currently no way to deploy a contract at an address of one's choosing.

b) Another option that would be actually doable would be to have this "savings contract factory" that creates vaults for people to only be able to extract after some time. The developer making the factory forgot to keep a reference to the deployed address of his first vault and, "oops", lost some money. it's your job to find out where the deployed contract ended up and try to recover it. The player would have to do some research into how "random" deployed addresses are, find out that they are actually not random, and then just go and recover the funds. The level maker would simply have to check the balance of this "lost" contract to be zero for the level to pass. I think this would be a clearer gameplay than what you currently have, and with a more realistic scenario.

I only mention option "a" out of curiosity and in case you have an awesome idea that could make it work. Otherwise, if you want to do a new PR with option B, be my guest. Otherwise I can do it if you like and of course give you all the credit because it was your idea.

Sorry that I don't just merge this PR. I think the idea is great, but it could be taken further.
Thx again, this is going to be a great level =D

**Comment by AgeManning** [comment]
Hey @ajsantander, 
Thanks for getting back to this. Totally understand the time constraints, I'm much the same. I remember back when I was making this that level was a little convoluted, so I agree with your suggestions for building scenario (b). It should be easy to implement so hopefully I'll have some time this week or the next to modify this. 

In regards to (a) - It would be a serious issue if one could simply choose the address at which a contract is to be deployed. Luckily, the create2 opcode to be introduced doesn't allow you to arbitrarily choose an address. It just allows you specify a new parameter,n, which kind of acts like a nonce. i.e the new contract address is still a keccak hash of (<address>.n. <hash-of-code>). Although this now makes me wonder, it seems now you can steal ether from any account if you can find an n such that keccak(<address>.n.<hash-of-code>) equals the address. Although this is a VERY difficult problem to solve, it seems to be less time complex (i.e each guess involves only 2 hashes) than brute forcing elliptic curve private keys to find the associated address (which requires elliptic curve multiplication and a subsequent hash). I might look into this also... 

Anyway, expect an updated level at some stage in the near future. 

Also, thanks for making these challenges. They are a very useful addition to the community and solidity devs in general :)

**Comment by ajsantander** [comment]
Splendid! Eager to see more about this.

This topic could be a big area of exploration in ethernaut.

**Comment by AgeManning** [comment]
Hey @ajsantander , 

I've had some more time, and read option (b) a little more carefully. As I understand, you are suggesting that, there be a "vault factory" contract, which produces "vault" contracts (which have some withdraw function). The factory makes a few of them, but loses track of the first, i.e the contract address. The user needs to find the contract address and call withdraw.  Is my understanding correct?

I'm happy to implement this, however there was one extra element of this challenge I thought would be interesting to showcase. Simply the fact that you can send ether to a pre-determined address which seemingly is un-recoverable (there is no code at that address) unless you have the private key. If you chose the address correctly, you can then write a contract that can be deployed at that address and retrieve the ether, without ever having the private key of the address. This way users can see ether in an address, which has no code and magically watch as the ether gets withdrawn without a private key to the address which previously contained no code. As Martin Swende discusses in the post I reference, you can use this to hide ether in addresses which you never own the private key to (and in some circumstances have plausible deniability over ownership of that ether). It is also a technique to hide ether in an empty account (i.e the empty account can create a contract to recover the ether at a derived address at nonce 2 for example) such that if someone forcibly took possession of your private key, and they unwittingly did 3 transactions, your hidden ether would be lost forever. 

I'm not sure if this kind of technique is interesting, or if you prefer to stick with the simpler approach you suggested for the Ethernaught challenges. 

Let me know what you think. 

Cheers

**Comment by ajsantander** [comment]
My suggestion is that the vault factory (level instance) is flawed and deploys vaults (meta instances) without returning their deployed addresses.

A user calls a payable deploy vault and loses the money because they dont know were the vault is.

The level (factory) does know and determines if the player wins when the vault deployed has no funds, because the player found it and withdrew the funds.

**Comment by ajsantander** [comment]
@AgeManning please note that I don't want to hold you back with this. This will be a great level because of what it teaches the player, no matter the "story" around it. 

Lets find a practical solution so that we can merge this level. What would you like to do?

**Comment by AgeManning** [comment]
Hey @ajsantander, 

Sorry for the massive delay. I will implement the changes now and fix this. :)

**Comment by ajsantander** [comment]
On the contrary, sorry for complicating it unnecessarily! Thanks for persevering. Will be merging this one manually too.

**Pull request merged**
