### PR TITLE
added network support for holesky

### PR DESCRIPTION
**Pull request by garv-aga**
**This pull request make the following changes:**
* Fixes issue #692

### CODE REVIEW

**Review by GianfrancoBazzani — APPROVED** [review]
LGTM!

**Comment by GianfrancoBazzani** [comment]
Hey @garv-aga thanks for your contribution! ^^. We need to receive the ownership of the statistics  `ProxyAdmin`contract though before merge the PR. 

Please transfer the ownership of `0x8f3189256cb686D0aCD642bAa3982Fda156fB01D` to Ethernaut's owner address: `0x09902A56d04a9446601a0d451E07459dC5aF0820`

**Comment by garv-aga** [comment]
> Hey @garv-aga thanks for your contribution! ^^. We need to receive the ownership of the statistics `ProxyAdmin` contract before merge the PR.
> 
> Please transfer the ownership of `0x8f3189256cb686D0aCD642bAa3982Fda156fB01D` to Ethernaut's owner address: `0x09902A56d04a9446601a0d451E07459dC5aF0820`

I transferred the ownership.

Thanks for the opportunity

**Review by xaler5 — APPROVED** [review]

**Comment by xaler5** [comment]
LGTM! thanks :heart:

**Pull request merged**
