### PR TITLE
simplified Chinese translation

### PR DESCRIPTION
**Pull request by sunrentao**

### CODE REVIEW

**Comment by frangio** [comment]
Thank you @sunrentao! Is this a work in progress?

Can you translate the `"info"` string so the homepage is translated? Ideally, I think at least the "Hello Ethernaut" level should be translated as well.

**Comment by sunrentao** [comment]
> Thank you @sunrentao! Is this a work in progress?
> 
> Can you translate the `"info"` string so the homepage is translated? Ideally, I think at least the "Hello Ethernaut" level should be translated as well.

Hi, frangio. 
Yes, this work is in progress, I am making it with my spare time. 
And I have translated the part you were saying.

**Comment by frangio** [comment]
>Yes, this work is in progress, I am making it with my spare time.

That's fine, it's appreciated. I'm going to make this into a Draft PR. Please let us know when you think it's at a point that could be merged. Not all levels need to be translated.

**Comment by sunrentao** [comment]
Hi, I have translated to level 9, and the help page. Maybe we can merge now? After deploy, I can also check it in web which is better. And I will continue to  translate other level .

**Comment by frangio** [comment]
Yeah, sure! Thank you!

**Comment by xaler5** [comment]
thanks everyone !

**Pull request merged**
